var provinceList = [
    {
        name:'中西药品',
        id:'A',
        cityList:[
            {
                name:'五官用药',
                id:'Aa',
                areaList:
                    [
                        {
                            "id":"Aa01",
                            "name":"牙周疾病"
                        },
                        {
                            "id":"Aa02",
                            "name":"眼药水膏"
                        },
                        {
                            "id":"Aa03",
                            "name":"耳鼻科用药"
                        },
                        {
                            "id":"Aa04",
                            "name":"口腔疾病"
                        }
                    ]
            },

            {
                "id": "Ab",
                "name": "感冒发热",
                areaList:
                    [
                        {
                            "id":"Ab01",
                            "name":"头痛发烧"
                        },
                        {
                            "id":"Ab02",
                            "name":"中暑发烧"
                        },
                        {
                            "id":"Ab03",
                            "name":"咽喉肿痛"
                        },
                        {
                            "id":"Ab04",
                            "name":"止咳化痰'"
                        },
                        {
                            "id":"Ab05",
                            "name":"清热解毒"
                        },
                        {
                        "id":"Ab06",
                        "name":"鼻塞流涕"
                        },
                        {
                            "id":"Ab07",
                            "name":"消炎清热"
                        }
                    ]
            },
            {
                "id": "Ac",
                "name": "呼吸系统",
                areaList:
                    [
                        {
                            "id":"Ac01",
                            "name":"鼻腔护理"
                        },
                        {
                            "id":"Ac02",
                            "name":"哮喘咳喘"
                        },
                        {
                            "id":"Ac03",
                            "name":"咽炎气管炎"
                        },
                        {
                            "id":"Ac04",
                            "name":"呼吸道感染"
                        },
                        {
                            "id":"Ac05",
                            "name":"养肺用药"
                        }
                    ]
            },
            {
                "id": "Ad",
                "name": "消化系统",
                areaList:
                    [
                        {
                            "id":"Ad01",
                            "name":"急慢性胃炎"
                        },
                        {
                            "id":"Ad02",
                            "name":"腹泻腹痛"
                        },
                        {
                            "id":"Ad03",
                            "name":"胃溃疡"
                        },
                        {
                            "id":"Ad04",
                            "name":"健胃消食"
                        },
                        {
                            "id":"Ad05",
                            "name":"急慢性肠炎"
                        },
                        {
                            "id":"Ad06",
                            "name":"痔疮便秘"
                        },
                        {
                            "id":"Ad07",
                            "name":"制酸止痛"
                        },
                        {
                            "id":"Ad08",
                            "name":"食管炎"
                        },
                        {
                            "id":"Ad09",
                            "name":"肝胆胰"
                        },
                        {
                            "id":"Ad10",
                            "name":"驱虫"
                        }
                    ]
            },
            {
                "id": "Ae",
                "name": "风湿骨伤",
                areaList:
                    [
                        {
                            "id":"Ae01",
                            "name":"筋骨疼痛"
                        },
                        {
                            "id":"Ae02",
                            "name":"跌打损伤"
                        },
                        {
                            "id":"Ae03",
                            "name":"颈椎病"
                        },
                        {
                            "id":"Ae04",
                            "name":"关节炎"
                        },
                        {
                            "id":"Ae05",
                            "name":"腰肌劳损"
                        },
                        {
                            "id":"Ae06",
                            "name":"骨质疏松"
                        },
                        {
                            "id":"Ae07",
                            "name":"骨质增生"
                        },
                        {
                            "id":"Ae08",
                            "name":"痛风"
                        }
                    ]
            },
            {
                "id": "Af",
                "name": "维生素矿物质",
                areaList:
                    [
                        {
                            "id":"Af01",
                            "name":"提高免疫力"
                        },
                        {
                            "id":"Af02",
                            "name":"维生素矿物质"
                        },
                        {
                            "id":"Af03",
                            "name":"叶酸"
                        },
                        {
                            "id":"Af04",
                            "name":"钙铁锌硒"
                        },
                        {
                            "id":"Af05",
                            "name":"失眠安神"
                        },
                        {
                            "id":"Af06",
                            "name":"补气补血"
                        },
                        {
                            "id":"Af07",
                            "name":"生发乌发"
                        },
                        {
                            "id":"Af08",
                            "name":"营养类"
                        },
                        {
                            "id":"Af09",
                            "name":"滋阴补肾"
                        },
                        {
                            "id":"Af10",
                            "name":"保胎促孕"
                        }
                    ]
            },
            {
                "id": "Ag",
                "name": "皮肤外用",
                areaList:
                    [
                        {
                            "id":"Ag01",
                            "name":"皮肤瘙痒"
                        },
                        {
                            "id":"Ag02",
                            "name":"痤疮祛痘"
                        },
                        {
                            "id":"Ag03",
                            "name":"白癜风银屑病"
                        },
                        {
                            "id":"Ag04",
                            "name":"烧伤烫伤"
                        },
                        {
                            "id":"Ag05",
                            "name":"皮炎湿疹"
                        },
                        {
                            "id":"Ag06",
                            "name":"蚊虫叮咬"
                        },
                        {
                            "id":"Ag07",
                            "name":"消炎"
                        },
                        {
                            "id":"Ag08",
                            "name":"脚气灰指甲"
                        },
                        {
                            "id":"Ag09",
                            "name":"廯疱疹"
                        },
                        {
                            "id":"Ag10",
                            "name":"抗过敏"
                        }
                    ]
            },
            {
                "id": "Ah",
                "name": "儿科用药",
                areaList:
                    [
                        {
                            "id":"Ah01",
                            "name":"小二感冒"
                        },
                        {
                            "id":"Ah02",
                            "name":"儿童维生素"
                        },
                        {
                            "id":"Ah03",
                            "name":"抗菌消炎"
                        },
                        {
                            "id":"Ah04",
                            "name":"钙铁锌矿物质"
                        },
                        {
                            "id":"Ah05",
                            "name":"咳嗽哮喘"
                        },
                        {
                            "id":"Ah06",
                            "name":"厌食补益"
                        },
                        {
                            "id":"Ah07",
                            "name":"腹泻便秘"
                        },
                        {
                            "id":"Ah08",
                            "name":"健脾消食"
                        },
                        {
                            "id":"Ah09",
                            "name":"驱虫"
                        },
                        {
                            "id":"Ah10",
                            "name":"小儿祛火"
                        },
                        {
                            "id":"Ah11",
                            "name":"鼻腔护理"
                        },
                        {
                            "id":"Ah12",
                            "name":"小儿过敏"
                        }
                    ]
            },
            {
                "id": "Ai",
                "name": "心脑血管",
                areaList:
                    [
                        {
                            "id":"Ai01",
                            "name":"脑血管病"
                        },
                        {
                            "id":"Ai02",
                            "name":"高血压高血脂"
                        },
                        {
                            "id":"Ai03",
                            "name":"心律失常"
                        },
                        {
                            "id":"Ai04",
                            "name":"糖尿病"
                        },
                        {
                            "id":"Ai05",
                            "name":"外周血管疾病"
                        },
                        {
                            "id":"Ai06",
                            "name":"冠心病"
                        },
                        {
                            "id":"Ai07",
                            "name":"动脉硬化"
                        },
                        {
                            "id":"Ai08",
                            "name":"中风"
                        },
                        {
                            "id":"Ai09",
                            "name":"心力衰竭"
                        },
                        {
                            "id":"Ai10",
                            "name":"心绞痛"
                        },
                        {
                            "id":"Ai11",
                            "name":"心梗脑梗"
                        },
                        {
                            "id":"Ai12",
                            "name":"静脉曲张"
                        }
//
                    ]
            },
            {
                "id": "Aj",
                "name": "妇科男科",
                areaList:
                    [
                        {
                            "id":"Aj01",
                            "name":"避孕药"
                        },
                        {
                            "id":"Aj02",
                            "name":"减肥"
                        },
                        {
                            "id":"Aj03",
                            "name":"外用洗液栓剂"
                        },
                        {
                            "id":"Aj04",
                            "name":"止血化瘀"
                        },
                        {
                            "id":"Aj05",
                            "name":"带下恶露"
                        },
                        {
                            "id":"Aj06",
                            "name":"乳腺疾病"
                        },
                        {
                            "id":"Aj07",
                            "name":"妇科炎症"
                        },
                        {
                            "id":"Aj08",
                            "name":"调经补益"
                        },
                        {
                            "id":"Aj09",
                            "name":"更年期"
                        },
                        {
                            "id":"Aj10",
                            "name":"外用洗液"
                        },
                        {
                            "id":"Aj11",
                            "name":"补肾壮阳"
                        },
                        {
                            "id":"Aj12",
                            "name":"前列腺"
                        }
                    ]
            },
          
            {
                "id": "Am",
                "name": "其他",
                areaList:
                    [
                        {
                            "id":"Am01",
                            "name":"甲状腺疾病"
                        },
                        {
                            "id":"Am02",
                            "name":"抗癌药"
                        },
                        {
                            "id":"Am03",
                            "name":"抗排异"
                        },
                        {
                            "id":"Am04",
                            "name":"戒烟戒酒"
                        },
                        {
                            "id":"Am05",
                            "name":"止痛"
                        },
                        {
                            "id":"Am06",
                            "name":"其他"
                        }
                    ]
            },
            {
                "id": "An",
                "name": "抗生素",
                areaList:
                    [
                        {
                            "id":"An01",
                            "name":"广谱抗生素"
                        },
                        {
                            "id":"An02",
                            "name":"青霉素"
                        },
                        {
                            "id":"An03",
                            "name":"头孢菌素"
                        },
                        {
                            "id":"An04",
                            "name":"四环素"
                        },
                        {
                            "id":"An05",
                            "name":"大环内酯"
                        },
                        {
                            "id":"An06",
                            "name":"硝基咪唑"
                        },
                        {
                            "id":"An07",
                            "name":"抗病毒"
                        },
                        {
                            "id":"An08",
                            "name":"抗结核"
                        },
                        {
                            "id":"An09",
                            "name":"其他抗生素"
                        }
                    ]
            },
            {
                "id": "Ap",
                "name": "清热除湿",
                areaList:
                    [
                        {
                            "id":"Ap01",
                            "name":"清热泻火"
                        },
                        {
                            "id":"Ap02",
                            "name":"清热祛热"
                        },
                        {
                            "id":"Ap03",
                            "name":"疮疡肿痛"
                        },
                        {
                            "id":"Ap04",
                            "name":"其他清热泻火"
                        }
                    ]
            },
            {
                "id": "Aq",
                "name": "泌尿",
                areaList:
                    [
                        {
                            "id":"Aq01",
                            "name":"尿崩症"
                        },
                        {
                            "id":"Aq02",
                            "name":"尿频尿急"
                        },
                        {
                            "id":"Aq03",
                            "name":"尿路感染"
                        },
                        {
                            "id":"Aq04",
                            "name":"尿路结石"
                        },
                        {
                            "id":"Aq05",
                            "name":"肾功能不全"
                        },
                        {
                            "id":"Aq06",
                            "name":"肾病综合"
                        }
                    ]
            },
            {
                "id": "Ar",
                "name": "免疫系统",
                areaList:
                    [
                        {
                            "id":"Ar01",
                            "name":"紫癜红斑狼疮"
                        },
                        {
                            "id":"Ar02",
                            "name":"化疗药"
                        },
                        {
                            "id":"Ar03",
                            "name":"免疫调节"
                        },
                        {
                            "id":"Ar04",
                            "name":"其他免疫用药"
                        }
                    ]
            },
            {
                "id": "As",
                "name": "糖尿病",
                areaList:
                    [
                        {
                            "id":"As01",
                            "name":"降糖药"
                        },
                        {
                            "id":"As02",
                            "name":"糖尿病并发症"
                        }
                    ]
            },
            {
                "id": "At",
                "name": "肝胆肾脾",
                areaList:
                    [
                        {
                            "id":"At01",
                            "name":"养肝系列"
                        },
                        {
                            "id":"At02",
                            "name":"养肾系列"
                        },
                        {
                            "id":"At03",
                            "name":"养胆系列"
                        },
                        {
                            "id":"At04",
                            "name":"养脾系列"
                        }
                    ]
            }


        ]
    },

    {
        name:'医疗器械',
        id:'B',
        cityList:[
            {
                name:'血糖用品',
                id:'Ba',
                areaList:
                    [
                        {
                            "id":"Ba01",
                            "name":"血糖仪"
                        },
                        {
                            "id":"Ba02",
                            "name":"血糖试纸"
                        },
                        {
                            "id":"Ba03",
                            "name":"胰岛素笔"
                        },
                        {
                            "id":"Ba04",
                            "name":"胰岛素针头"
                        }
                    ]
            },
            {
                id:'Bb',
                name:'血压计',
                areaList:
                    [
                        {
                            "id":"Bb01",
                            "name":"臂式"
                        },
                        {
                            "id":"Bb02",
                            "name":"腕式"
                        },
                        {
                            "id":"Bb03",
                            "name":"语音"
                        },
                        {
                            "id":"Bb04",
                            "name":"水银"
                        }
                    ]
            },
            {
                name:'制氧器材',
                id:'Bc',
                areaList:
                    [
                        {
                            "id":"Bc01",
                            "name":"制氧机"
                        },
                        {
                            "id":"Bc02",
                            "name":"氧气瓶/袋/管"
                        },
                        {
                            "id":"Bc03",
                            "name":"制氧制剂"
                        },
                        {
                            "id":"Bc04",
                            "name":"制氧器"
                        }
                    ]
            },
            {
                name:'保健理疗',
                id:'Bd',
                areaList:
                    [
                        {
                            "id":"Bd01",
                            "name":"针灸/艾灸"
                        },
                        {
                            "id":"Bd02",
                            "name":"拔罐/刮痧"
                        },
                        {
                            "id":"Bd03",
                            "name":"足浴盆/足浴盐"
                        },
                        {
                            "id":"Bd04",
                            "name":"按摩器"
                        },
                        {
                            "id":"Bd05",
                            "name":"煎药器"
                        },
                        {
                            "id":"Bd06",
                            "name":"保健枕"
                        },
                        {
                            "id":"Bd07",
                            "name":"空气净化器"
                        },
                        {
                            "id":"Bd08",
                            "name":"保健贴膏"
                        },
                        {
                            "id":"Bd09",
                            "name":"理疗仪"
                        }
                    ]
            },
            {
                name:'康复护理',
                id:'Be',
                areaList:
                    [
                        {
                            "id":"Be01",
                            "name":"护具/护带"
                        },
                        {
                            "id":"Be02",
                            "name":"成人尿裤/护理垫/造口护理"
                        },
                        {
                            "id":"Be03",
                            "name":"便椅/便器"
                        },
                        {
                            "id":"Be04",
                            "name":"医用手套/消毒"
                        },
                        {
                            "id":"Be05",
                            "name":"助听器"
                        },
                        {
                            "id":"Be06",
                            "name":"轮椅/助行/拐杖"
                        },
                        {
                            "id":"Be07",
                            "name":"医用弹力袜"
                        }
                    ]
            },
            {
                name:'辅助治疗',
                id:'Bf',
                areaList:
                    [
                        {
                            "id":"Bf01",
                            "name":"颈椎牵手"
                        },
                        {
                            "id":"Bf02",
                            "name":"疝气治疗"
                        },
                        {
                            "id":"Bf03",
                            "name":"保健治疗仪/器"
                        },
                        {
                            "id":"Bf04",
                            "name":"注射器"
                        },
                        {
                            "id":"Bf05",
                            "name":"雾化器/配件"
                        },
                        {
                            "id":"Bf06",
                            "name":"阻鼾器"
                        },
                        {
                            "id":"Bf07",
                            "name":"紫外线灯"
                        }
                    ]
            },
            {
                name:'家庭常备',
                id:'Bg',
                areaList:
                    [
                        {
                            "id":"Bg01",
                            "name":"体温计/口罩"
                        },
                        {
                            "id":"Bg02",
                            "name":"贴膏"
                        },
                        {
                            "id":"Bg03",
                            "name":"创可贴/纱布/绷带/胶带"
                        },
                        {
                            "id":"Bg04",
                            "name":"消毒/棉签/棉球"
                        },
                        {
                            "id":"Bg05",
                            "name":"退热贴/晕车贴/通气鼻贴"
                        },
                        {
                            "id":"Bg06",
                            "name":"冲洗器"
                        },
                        {
                            "id":"Bg07",
                            "name":"家用急救箱/药盒"
                        },
                        {
                            "id":"Bg08",
                            "name":"其他"
                        }
                    ]
            },
            {
                name:'日常监测',
                id:'Bh',
                areaList:
                    [
                        {
                            "id":"Bh01",
                            "name":"胎心计"
                        },
                        {
                            "id":"Bh02",
                            "name":"血氧仪"
                        },
                        {
                            "id":"Bh03",
                            "name":"早孕测试纸"
                        },
                        {
                            "id":"Bh04",
                            "name":"计步器"
                        },
                        {
                            "id":"Bh05",
                            "name":"听诊器/配件"
                        },
                        {
                            "id":"Bh06",
                            "name":"体重/体脂监测"
                        },
                        {
                            "id":"Bh07",
                            "name":"家用急救箱/药盒"
                        },
                        {
                            "id":"Bh08",
                            "name":"其他"
                        }
                    ]
            },
            {
                name:'其他医疗器械',
                id:'Bi',
                areaList:
                    []
            }

        ]
    },
    {
        name:'养生保健',
        id:'C',
        cityList:[
            {
                name:'机能改善',
                id:'Ca',
                areaList:
                    [

                    ]
            },

            {
                id:'Cb',
                name:'参茸滋补',
                areaList:
                    [

                    ]
            },
            {
                id:'Cc',
                name:'中药饮片',
                areaList:
                    [

                    ]
            },
            {
                id:'Cd',
                name:'维矿',
                areaList:
                    [

                    ]
            },
            {
                id:'Ce',
                name:'其他养生保健',
                areaList:
                    [

                    ]
            }
        ]
    },
    {
        name:'母婴',
        id:'D',
        cityList:[
            {
                name:'儿童用药',
                id:'Da',
                areaList:
                    [

                    ]
            },

            {
                id:'Db',
                name:'奶粉',
                areaList:
                    [

                    ]
            },
            {
                name:'营养辅食',
                id:'Dc',
                areaList:
                    [

                    ]
            },
            {
                name:'维矿',
                id:'Dd',
                areaList:
                    [

                    ]
            },
            {
                name:'其他母婴类产品',
                id:'De',
                areaList:
                    [

                    ]
            }

        ]
    }
]